[project]
name = "job-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
    "requests>=2.34.2",
    "requests-html>=0.10.0",
    "selenium>=4.48.0",
    "streamlit>=1.62.0",
]

[dependency-groups]
dev = [
    "ipython>=9.16.1",
    "ruff>=0.16.6",
]
